---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boa-manager
  namespace: boa
  labels:
    app: boa-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boa-manager
  template:
    metadata:
      labels:
        app: boa-manager
    spec:
      containers:
      - name: boa-manager
        image: boa-manager:test
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_HOSTNAME
            value: postgresql.boa.svc.cluster.local
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: test
          - name: DB_PORT
            value: '5432'
          - name: DB_NAME
            value: boa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: boa-manager
  name: boa-manager
  namespace: boa
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: boa-manager
  type: ClusterIP