---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-client
  namespace: boa
  labels:
    app: dev-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-client
  template:
    metadata:
      labels:
        app: dev-client
    spec:
      containers:
      - name: dev-client
        image: redhat/ubi9-minimal:9.2
        args:
        - sleep
        - infinity
        volumeMounts:
        - mountPath: /app
          name: app
      volumes:
      - name: app
        hostPath:
          path: /run/desktop/mnt/host/c/Users/aleja/OneDrive/Documents/ci-application/boa-client
