---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
  namespace: boa
  labels:
    app: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: dev
        image: redhat/ubi9-minimal:9.2
        args:
        - sleep
        - infinity
        volumeMounts:
        - mountPath: /app
          name: app
      volumes:
      - name: app
        hostPath:
          path: /run/desktop/mnt/host/c/Users/aleja/OneDrive/Documents/ci-application/boa-manager-real
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev
  name: dev
  namespace: boa
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: dev
  type: ClusterIP