apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: boa
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:14.6
        env:
        - name: POSTGRES_PASSWORD
          value: test
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: boa
spec:
  selector:
    app: postgresql
  ports:
  - name: postgresql
    protocol: TCP
    port: 5432
    targetPort: postgresql