apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: boa
  name: boa-manager
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: 
  - "pods"
  verbs: 
  - "get"
  - "watch"
  - "list"
  - "create"
  - "delete"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boa-manager
  namespace: boa
---
apiVersion: v1
kind: Secret
metadata:
  name: boa-manager
  namespace: boa
  annotations:
    kubernetes.io/service-account.name: boa-manager
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: boa-manager
  namespace: boa
subjects:
- kind: ServiceAccount
  name: boa-manager
  namespace: boa
roleRef:
  kind: Role
  name: boa-manager
  apiGroup: rbac.authorization.k8s.io