-- DATABASE SETUP --
CREATE DATABASE boa;

-- ORGANIZATIONS --
CREATE TABLE organizations (
	organization_id serial PRIMARY KEY,
	organization_name VARCHAR ( 50 ) UNIQUE NOT NULL
);

-- CLUSTERS (token, ca, server url) --
CREATE TABLE clusters (
    cluster_id serial PRIMARY KEY,
    cluster_name VARCHAR ( 50 ) UNIQUE NOT NULL,
    server_url VARCHAR ( 50 ) NOT NULL,
    certificate_authority VARCHAR ( 2048 ) NOT NULL,
    token VARCHAR ( 2048 ) NOT NULL
);

-- JOBS --
CREATE TABLE jobs (
	job_id serial PRIMARY KEY,
	job_name VARCHAR ( 50 ) NOT NULL,
    organization_id serial REFERENCES organizations (organization_id),
    cluster_id serial REFERENCES clusters (cluster_id)
);

-- CREATE ORGANIZATION --
INSERT INTO organizations (organization_name) VALUES ('test');
CREATE UNIQUE INDEX unique_org_jobs_<organization_id>
    ON jobs (job_name)
        WHERE organization_id = <organization_id>;
        
-- CREATE CLUSTER REFERENCE --
INSERT INTO clusters (cluster_name, server_url, certificate_authority, token) 
    VALUES (
        'default',
        'https://kubernetes.docker.internal:6443', 
        'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EZ3dNVEExTWpFMU9Wb1hEVE16TURjeU9UQTFNakUxT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS29WCnNORW1SVmdDbVBlemVhVU9KRXB6ZllDUXhGM2loYU94elJUU2NIM1ZENThaSTcrL2w3TU1Jd0J5M1BtNkNPWFkKQmVBYWdpRDlWRW4zOVo4dDgva2tQdWc4c1FBVHZWQVZrNVI5cnhWRm1YSGE4WXhRNENKWVNRMWxiWHMvRzJrUwpPZWhyOEw5Qm9vY01TVC9BNzdVQjI4YUM2bUVpR0xUU1Z3a1pCOHBYalk2RkF5RXhFcFY0SjJUYkE5eFYyL2YyClZiZXpPVUtpU1doSE1xZDB2MWpXUFZvejYxbkxydUJjOURiRFU3a2lscUZ2aXFoQWdJdFpVZDlkb0dwNHFXWkQKMkhENEZaTVlQUjdkRTZWaFRzMHZ3Y2xoNzMxVFh1ZGlyRzc2ZFp5KzNkS1E1TnN4dDV2Ky9DaFBqTGY5QTlBNgpzQ0pHeVJuSGRqUThEdS9PWVBjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZPSXBIdXhncWNNYUg0ZElzYWN4bjIyOWpaWTJNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRnc5ZUhzM0IxWnZ3SkZBTk5FQQpRbjdUN1dBb3dSWFFrQmxvLytPTEQ4Q09HdXp1K0hobUhFcVR3bzRIRVNyWXBNUjRuelQrTS8xOTluaW5NUktNCmZCUVY4MGQ1U2p1ZjNjSHVVY0pMQVVadzRrdXUxdk9CZGx3Mk1wRVhyR3ByQWdyMzNLT1k5SW9ZeGUwZzJ4NFcKbzQ5KzZCR3hhNFFCeG00ZmdPb25TUklUbVoreXdCOW84WjBYeTQ2dXRKZzlwTG5xb0NvS0Ywd2MreFplL0lwZwo5WmV2V0w0T3JSSTJSWWJaTTl3eFV2a09BMTc3YTYwY0ZSQVpWdUJQcFAzRkpaUnIzV0JZQ3pqZXZhZVRUZGplCkI4WGlackMrU2pHdk02bHV1YTRXT2xBNmNiQXAvb1FJTDY2Z2JDcnFEeW91SWxUeXA3WXdaRTc0dWx1WEdNbzcKL0xvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==',
        'eyJhbGciOiJSUzI1NiIsImtpZCI6Inl1ell6REEtRjZ4b0V2Wmp3YkRHemhZd0hvTDNVZ1lIYm4weGYzVzZjczgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJib2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiYm9hLW1hbmFnZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYm9hLW1hbmFnZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJjNjk3ZmVhMS1jMjE5LTQ4MzctYjk1ZS00ODQzZmYzNGU5MGEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Ym9hOmJvYS1tYW5hZ2VyIn0.eEzUYDz56qsY_QYCnuQrS6QE2deWPKgxRpPISiPiXgef8LM0EQkRyWi6ZiLyXH2PkZGKL03AckLswVXQeQbnYXn0HDn249Df_bNQucfrYMQqy84VFAhseERiix1uNlnunLH_lM-tHRPnNpgobwS70Gu8d6E1S99dGdas7Ozyz0ej36UyyGmLJsj0BfgEYHHrI5aOa7PbN9zMqSv5C-fV-Qz3jCU_GdhGDDUMcM7B6kO7yHgQiMO-uP3sPYcKOldAp8LkXKoc-o9pnLvBs7w2ykneh1JzwF2aV1UpLBY5SnsEKh8kR2JgjFEj8duqFskr7fBDlnMCcjBMp4iwp1ivRQ'
    );

-- CREATE A JOB (References an Organization and Cluster) --    
INSERT INTO jobs (job_name, organization_id, cluster_id) VALUES ('test', 1, 2);

